// Auto-generated by sync-locations.js — do not edit manually.
window.LOCATION_COUNT = 209;
(function(){function a(){var e=document.getElementById('footerCount');if(e)e.textContent=window.LOCATION_COUNT;}if(document.readyState==='loading'){document.addEventListener('DOMContentLoaded',a);}else{a();}})();
