// ─────────────────────────────────────────────────────────────────────────────
// migrate-photos.js
// One-time script: downloads the first Google Places photo for each location
// and saves it to /images/locations/{id}.jpg, then updates locations.js with
// a `localImage` field so pages no longer need live Places API calls for photos.
//
// Usage:
//   GOOGLE_PLACES_API_KEY=your_key node migrate-photos.js
//
// Safe to re-run — already-migrated locations are skipped automatically.
// ─────────────────────────────────────────────────────────────────────────────

const fs   = require('fs');
const path = require('path');

// Load .env
try {
  fs.readFileSync(path.join(__dirname, '.env'), 'utf8').split('\n').forEach(line => {
    const eq = line.indexOf('=');
    if (eq > 0) process.env[line.slice(0, eq).trim()] = line.slice(eq + 1).trim().replace(/^"|"$/g, '');
  });
} catch {}

const API_KEY        = process.env.GOOGLE_PLACES_API_KEY;
const LOCATIONS_FILE = path.join(__dirname, 'locations.js');
const IMAGES_DIR     = path.join(__dirname, 'images', 'locations');
const DELAY_MS       = 250; // pause between requests to avoid rate limiting

function sleep(ms) {
  return new Promise(resolve => setTimeout(resolve, ms));
}

async function downloadPhoto(photoName, destPath) {
  const url = `https://places.googleapis.com/v1/${photoName}/media?maxWidthPx=1200&key=${API_KEY}`;
  const res = await fetch(url);
  if (!res.ok) throw new Error(`HTTP ${res.status} ${res.statusText}`);
  const buffer = await res.arrayBuffer();
  fs.writeFileSync(destPath, Buffer.from(buffer));
}

async function fetchPhotoRef(placeId) {
  const url = `https://places.googleapis.com/v1/places/${placeId}?fields=photos&key=${API_KEY}`;
  const res = await fetch(url);
  if (!res.ok) throw new Error(`HTTP ${res.status} ${res.statusText}`);
  const data = await res.json();
  return (data.photos || []).slice(0, 5).map(p => ({
    name:     p.name,
    widthPx:  p.widthPx  || 0,
    heightPx: p.heightPx || 0,
  }));
}

async function main() {
  if (!API_KEY) {
    console.error('\n❌ Missing GOOGLE_PLACES_API_KEY');
    console.error('   Run: GOOGLE_PLACES_API_KEY=your_key node migrate-photos.js\n');
    process.exit(1);
  }

  // Create images directory if it doesn't exist
  if (!fs.existsSync(IMAGES_DIR)) {
    fs.mkdirSync(IMAGES_DIR, { recursive: true });
    console.log('  Created /images/locations/');
  }

  // Read and parse locations.js
  const raw   = fs.readFileSync(LOCATIONS_FILE, 'utf8');
  const match = raw.match(/window\.COFFEE_LOCATIONS\s*=\s*(\[[\s\S]*\]);/);
  if (!match) throw new Error('Could not parse window.COFFEE_LOCATIONS from locations.js');
  const locations = JSON.parse(match[1]);

  console.log(`\n📸 Migrating photos for ${locations.length} locations\n`);

  let downloaded = 0;
  let alreadyDone = 0;
  let noPhoto = 0;
  let failed = 0;
  const failures = [];

  for (const loc of locations) {
    const name = loc.basicInfo?.name || loc.id;

    // Skip if already migrated
    if (loc.localImage) {
      alreadyDone++;
      console.log(`  ⟳  ${name} (already migrated)`);
      continue;
    }

    // If image file already exists on disk, just register it without downloading
    const existingPath = path.join(IMAGES_DIR, `${loc.id}.jpg`);
    if (fs.existsSync(existingPath)) {
      loc.localImage = `/images/locations/${loc.id}.jpg`;
      downloaded++;
      console.log(`  ✓  ${name} (used existing file)`);
      continue;
    }

    // If no photo references stored, try fetching them from Places API using placeId
    let photos = loc.googlePhotos;
    if ((!photos || !photos.length || !photos[0]?.name) && loc.googleData?.placeId) {
      try {
        process.stdout.write(`  ⟳  ${name} (fetching photo ref) ... `);
        photos = await fetchPhotoRef(loc.googleData.placeId);
        loc.googlePhotos = photos;
        console.log(photos.length ? `got ${photos.length}` : 'none found');
        await sleep(DELAY_MS);
      } catch (err) {
        console.log(`✗  (${err.message})`);
      }
    }

    if (!photos || !photos.length || !photos[0]?.name) {
      noPhoto++;
      console.log(`  ○  ${name} (no photo reference)`);
      continue;
    }

    const destPath = path.join(IMAGES_DIR, `${loc.id}.jpg`);

    try {
      process.stdout.write(`  ↓  ${name} ... `);
      await downloadPhoto(photos[0].name, destPath);
      loc.localImage = `/images/locations/${loc.id}.jpg`;
      downloaded++;
      console.log('✓');
    } catch (err) {
      failed++;
      failures.push({ name, error: err.message });
      console.log(`✗  (${err.message})`);
    }

    await sleep(DELAY_MS);
  }

  // Write updated locations.js (preserving the same header format as sync-locations.js)
  const json   = JSON.stringify(locations, null, 2);
  const output = `// Auto-generated by sync-locations.js — do not edit the coffeeDetails blocks manually\n// Last synced: ${new Date().toLocaleString('en-US', { timeZone: 'America/Los_Angeles' })}\n\nwindow.COFFEE_LOCATIONS = ${json};\n`;

  fs.writeFileSync(LOCATIONS_FILE + '.backup', raw, 'utf8');
  fs.writeFileSync(LOCATIONS_FILE, output, 'utf8');

  // Summary
  console.log('\n─────────────────────────────');
  console.log(`✅ Done!`);
  console.log(`   Downloaded:      ${downloaded}`);
  console.log(`   Already done:    ${alreadyDone}`);
  console.log(`   No photo ref:    ${noPhoto}`);
  console.log(`   Failed:          ${failed}`);

  if (failures.length) {
    console.log('\n⚠️  Failed locations (photo references may have expired):');
    failures.forEach(f => console.log(`   - ${f.name}: ${f.error}`));
    console.log('\n   For failed locations, open the admin panel, re-save them to refresh');
    console.log('   the photo reference in Google Sheets, re-sync, then re-run this script.');
  }

  console.log('\nNext steps:');
  console.log('  git add images/locations/ locations.js');
  console.log('  git commit -m "Migrate location photos to self-hosted"');
  console.log('  git push\n');
}

main().catch(err => {
  console.error('\n❌ Migration failed:', err.message);
  process.exit(1);
});
