// One-off: switch loc_186 (Solana Coffee Company) from online-only to physical.
// Resolves the placeId via Places text search around the coords from the user's
// Maps URL, fetches details, and rewrites only the basicInfo/googleData/googleRating/
// hours blocks on loc_186 — coffeeDetails (including instagramReviewUrl) is preserved.
// Safe to delete after running.

const fs   = require('fs');
const path = require('path');

try {
  fs.readFileSync(path.join(__dirname, '.env'), 'utf8').split('\n').forEach(line => {
    const eq = line.indexOf('=');
    if (eq > 0) process.env[line.slice(0, eq).trim()] = line.slice(eq + 1).trim().replace(/^"|"$/g, '');
  });
} catch {}

const API_KEY   = process.env.GOOGLE_PLACES_API_KEY;
const LOC_FILE  = path.join(__dirname, 'locations.js');
const TARGET_ID = 'loc_186';
const KEEP_NAME = 'Solana Coffee Company';
const SEARCH    = { text: 'Solana Coffee at the Granger Hotel', lat: 32.7154057, lng: -117.1604511 };

if (!API_KEY) { console.error('GOOGLE_PLACES_API_KEY missing in .env'); process.exit(1); }

async function findPlaceId() {
  const res = await fetch('https://places.googleapis.com/v1/places:searchText', {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      'X-Goog-Api-Key': API_KEY,
      'X-Goog-FieldMask': 'places.id,places.displayName,places.formattedAddress'
    },
    body: JSON.stringify({
      textQuery: SEARCH.text,
      locationBias: { circle: { center: { latitude: SEARCH.lat, longitude: SEARCH.lng }, radius: 100 } }
    })
  });
  if (!res.ok) throw new Error(`Search HTTP ${res.status}: ${await res.text()}`);
  const data = await res.json();
  if (!data.places || !data.places.length) throw new Error('No search results');
  const p = data.places[0];
  console.log(`  Found: ${p.displayName?.text} (${p.id}) — ${p.formattedAddress}`);
  return p.id;
}

async function fetchDetails(placeId) {
  const fields = [
    'displayName','formattedAddress','location',
    'nationalPhoneNumber','websiteUri','googleMapsUri',
    'rating','userRatingCount','regularOpeningHours','addressComponents'
  ].join(',');
  const res = await fetch(`https://places.googleapis.com/v1/places/${placeId}?fields=${fields}&key=${API_KEY}`);
  if (!res.ok) throw new Error(`Details HTTP ${res.status}: ${await res.text()}`);
  return await res.json();
}

function parseAddress(components) {
  const get = (type, key = 'longText') => (components.find(c => c.types.includes(type)) || {})[key] || '';
  return {
    street: [get('street_number'), get('route')].filter(Boolean).join(' '),
    city:   get('locality') || get('sublocality_level_1'),
    state:  get('administrative_area_level_1', 'shortText'),
    zip:    get('postal_code')
  };
}

(async () => {
  console.log('Resolving placeId via text search...');
  const placeId = await findPlaceId();

  console.log('Fetching place details...');
  const place = await fetchDetails(placeId);
  const addr  = parseAddress(place.addressComponents || []);

  console.log('Reading locations.js...');
  const raw   = fs.readFileSync(LOC_FILE, 'utf8');
  const match = raw.match(/window\.COFFEE_LOCATIONS\s*=\s*(\[[\s\S]*\]);/);
  if (!match) throw new Error('Could not parse window.COFFEE_LOCATIONS');
  const locations = JSON.parse(match[1]);

  const loc = locations.find(l => l.id === TARGET_ID);
  if (!loc) throw new Error(`${TARGET_ID} not found`);

  // Drop the online-only amenity (the visitor-facing analog of the onlineOnly flag).
  if (Array.isArray(loc.coffeeDetails && loc.coffeeDetails.amenities)) {
    loc.coffeeDetails.amenities = loc.coffeeDetails.amenities.filter(a => !/online-only/i.test(a));
  }

  delete loc.basicInfo.onlineOnly;
  loc.basicInfo.name = KEEP_NAME;
  loc.basicInfo.address = {
    street:       addr.street,
    fullAddress:  place.formattedAddress || '',
    neighborhood: (loc.coffeeDetails && loc.coffeeDetails.neighborhood) || '',
    city:         addr.city,
    state:        addr.state,
    zip:          addr.zip,
    coordinates:  { lat: place.location?.latitude || 0, lng: place.location?.longitude || 0 }
  };
  loc.basicInfo.contact = {
    phone:         place.nationalPhoneNumber || '',
    website:       place.websiteUri          || (loc.basicInfo.contact && loc.basicInfo.contact.website) || '',
    googleMapsUrl: place.googleMapsUri       || ''
  };

  loc.googleData = { placeId, hasGoogleListing: true, lastSynced: new Date().toISOString() };
  loc.googleRating = { rating: place.rating || null, reviewCount: place.userRatingCount || 0 };
  loc.hours = { weekdayDescriptions: place.regularOpeningHours?.weekdayDescriptions || [], openNow: false };

  console.log('Writing locations.js (backup → locations.js.backup)...');
  fs.writeFileSync(LOC_FILE + '.backup', raw, 'utf8');
  const json   = JSON.stringify(locations);
  const output = `// Auto-generated by sync-locations.js — do not edit the coffeeDetails blocks manually\n// Last synced: ${new Date().toLocaleString('en-US', { timeZone: 'America/Los_Angeles' })}\n\nwindow.COFFEE_LOCATIONS = ${json};\n`;
  fs.writeFileSync(LOC_FILE, output, 'utf8');

  console.log('\n✓ Patched', TARGET_ID);
  console.log('  name:    ', loc.basicInfo.name);
  console.log('  placeId: ', placeId);
  console.log('  address: ', place.formattedAddress);
  console.log('  coords:  ', loc.basicInfo.address.coordinates);
  console.log('\nNext steps:');
  console.log('  1. Mirror in the Roasters sheet row for loc_186:');
  console.log('       - paste placeId =', placeId);
  console.log('       - remove "Online-only (no physical storefront)" from amenities');
  console.log('  2. Delete this script (patch-loc-186.js) once verified.');
})().catch(err => { console.error('\n✗ Failed:', err.message); process.exit(1); });
